### ISSUE TITLE
Real time update

### ISSUE THREAD

**Issue by dayjournal** [enricofer/attributepainter#10]
I have created a plugin called "AttributeAssignment".
Your plugin seems to be similar to my plugin.

Is it possible to display the drawing of the feature in real time?
For details, please check the gif image on the GitHub page.
https://github.com/dayjournal/AttributeAssignment

Can I add this code for updating?

` layer.triggerRepaint() `

**Comment by enricofer** [comment]
I see what you mean.
You would want to update map canvas on when attributes are applied.
https://github.com/enricofer/attributepainter/commit/794feacb3b1f8a00da9fadc9023f98e64603290b
Thanks for submission
