### ISSUE TITLE
Please update bugtracker address in metadata

### ISSUE THREAD

**Issue by pcav** [enricofer/attributepainter#2]
It still points to old hub.qgis.org

**Comment by enricofer** [comment]
https://github.com/enricofer/attributepainter/commit/859d9e1b06d3f6f1c55d3511a07f0dc9d20ec5e0

**Comment by pcav** [comment]
Sorry, I still see the old one. Could you please check?
Thanks.

**Comment by enricofer** [comment]
metadata file is ok so I manually changed the values on plugin.qgis.org

**Comment by pcav** [comment]
Thanks!
