### ISSUE TITLE
error when picking source feature without a current layer.

### ISSUE THREAD

**Issue by jef-n** [enricofer/attributepainter#4]
When clicking on "Pick source feature" without a selection in the layer tree or a group:

    Traceback (most recent call last):
      File "...\python\plugins\attributePainter\attributepainter.py", line 88, in selectSource
        if self.canvas.currentLayer().type() != QgsMapLayer.VectorLayer:
    AttributeError: 'NoneType' object has no attribute 'type'

**Comment by enricofer** [comment]
https://github.com/enricofer/attributepainter/commit/b676c6604ec2621c84802a8e6dc305eb10e5d2b4
thanks for submission
